"""H2' test analysis exactly per PROTOCOL_v2_H2.md section 7 (and section 4 for over-budget / failed runs).
Writes results/h2test_cells.csv, results/h2test_summary.md, results/h2test_verdict.json.  Solver env."""
import json
import os

import numpy as np
import pandas as pd

AREA = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(AREA, "results")
TIE = 1e-9
PLAN = json.load(open(os.path.join(RES, "plan_H2test.json")))
FIN = PLAN["ising_finalists"]
CLS = PLAN["classical"]
INST = [os.path.basename(p).replace(".npz", "") for p in PLAN["instances"]]
BUD = [1, 3, 10]
SEEDS = {m["solver"]: m["seeds"] for m in PLAN["methods"]}


def short(i):
    return i.replace("full_", "").replace("Region", "R")


def main():
    T = pd.read_csv(os.path.join(AREA, "trials.csv"))
    A = T[T.phase == "h2test"].copy()
    A["over_budget"] = A.over_budget.fillna(0).astype(int)
    ok = A[A.status == "ok"]
    # cells: per (instance, budget, method)
    cells = []
    for i in INST:
        for b in BUD:
            for m in FIN + CLS:
                x = A[(A.instance == i) & (A.budget == b) & (A.solver == m)]
                xo = x[x.status == "ok"]
                n_exp = len(SEEDS[m])
                n_fail = int((x.status != "ok").sum()) + max(0, n_exp - len(x))
                n_over = int(xo.over_budget.sum())
                valid = (n_fail == 0) and (n_over == 0) and len(xo) == n_exp
                mean = float(xo.objective.mean()) if len(xo) else np.nan
                cells.append(dict(instance=i, budget=b, method=m, n=len(xo), n_expected=n_exp, n_failed=n_fail,
                                  n_over_budget=n_over, mean=mean, sd=float(xo.objective.std(ddof=1)) if len(xo) > 1 else 0.0,
                                  obj_for_criteria=mean if valid else np.inf, valid=valid,
                                  wall_max=float(xo.wall.max()) if len(xo) else np.nan))
    C = pd.DataFrame(cells)
    C.to_csv(os.path.join(RES, "h2test_cells.csv"), index=False)
    # comparisons
    comp = []
    for i in INST:
        for b in BUD:
            cc = C[(C.instance == i) & (C.budget == b)]
            cl = cc[cc.method.isin(CLS)]
            best = cl.loc[cl.obj_for_criteria.idxmin()]
            for f in FIN:
                fv = float(cc[cc.method == f].obj_for_criteria.iloc[0])
                bv = float(best.obj_for_criteria)
                comp.append(dict(instance=i, budget=b, finalist=f, finalist_obj=fv, best_classical=best.method,
                                 classical_obj=bv, gap_pct=100 * (fv / bv - 1) if np.isfinite(fv) and np.isfinite(bv) else np.nan,
                                 le=bool(fv <= bv * (1 + TIE)), strict=bool(fv < bv * (1 - TIE))))
    K = pd.DataFrame(comp)
    K.to_csv(os.path.join(RES, "h2test_comparisons.csv"), index=False)
    verdict = {}
    out = ["# H2' test tables (generated by src/p2h2analyze.py)", ""]
    out.append("## Verdict per finalist (protocol section 7)")
    out.append("")
    out.append("| finalist | <= best classical: 1 s | 3 s | 10 s | budgets with >= 5/6 | (i) count | mean finalist (18 pairs) | mean best classical (18 pairs) | (ii) average | H2' |")
    out.append("|---|---|---|---|---|---|---|---|---|---|")
    for f in FIN:
        k = K[K.finalist == f]
        cnt = {b: int(k[k.budget == b]["le"].sum()) for b in BUD}
        strict = {b: int(k[k.budget == b]["strict"].sum()) for b in BUD}
        nb = sum(cnt[b] >= 5 for b in BUD)
        c1 = nb >= 2
        mf, mc = float(k.finalist_obj.mean()), float(k.classical_obj.mean())
        c2 = bool(mf < mc)
        verdict[f] = dict(counts=cnt, strict_counts=strict, budgets_meeting=nb, criterion_i=c1, mean_finalist=mf,
                          mean_best_classical=mc, criterion_ii=c2, H2prime=bool(c1 and c2))
        out.append(f"| {f} | {cnt[1]}/6 (strict {strict[1]}) | {cnt[3]}/6 (strict {strict[3]}) | {cnt[10]}/6 (strict {strict[10]}) | "
                   f"{nb} | {'pass' if c1 else 'FAIL'} | {mf:.4f} | {mc:.4f} | {'pass' if c2 else 'FAIL'} | "
                   f"**{'SUPPORTED' if c1 and c2 else 'NOT supported'}** |")
    out.append("")
    out.append("## Per-budget means over the 6 instances (method mean over seeds; best classical = per-cell minimum)")
    out.append("")
    out.append("| method | family | 1 s | 3 s | 10 s |")
    out.append("|---|---|---|---|---|")
    for m in FIN + CLS:
        row = []
        for b in BUD:
            x = C[(C.method == m) & (C.budget == b)]
            row.append(f"{x['mean'].mean():.4f}" + (f" [invalid cells {int((~x.valid).sum())}]" if (~x.valid).any() else ""))
        out.append(f"| {m} | {'Ising finalist' if m in FIN else 'classical'} | " + " | ".join(row) + " |")
    row = []
    for b in BUD:
        row.append(f"{K[(K.budget == b) & (K.finalist == FIN[0])].classical_obj.mean():.4f}")
    out.append("| best classical per cell | - | " + " | ".join(row) + " |")
    out.append("")
    out.append("## Per-cell comparison (finalist mean over seeds vs best classical mean; gap = finalist / classical - 1)")
    out.append("")
    out.append("| instance | budget | " + " | ".join(f"{f} (sd) | gap {f}" for f in FIN) + " | best classical (sd) | method |")
    out.append("|---|---|" + "---|---|" * len(FIN) + "---|---|")
    for i in INST:
        for b in [10, 3, 1]:
            cc = C[(C.instance == i) & (C.budget == b)].set_index("method")
            kk = K[(K.instance == i) & (K.budget == b)].set_index("finalist")
            bm = kk.best_classical.iloc[0]
            cells_f = []
            for f in FIN:
                g = kk.loc[f].gap_pct
                cells_f.append(f"{cc.loc[f, 'mean']:.4f} ({cc.loc[f, 'sd']:.4f})")
                cells_f.append(f"{g:+.3f}%{' <=' if kk.loc[f]['le'] else ''}" if np.isfinite(g) else "n/a")
            out.append(f"| {short(i)} | {b} | " + " | ".join(cells_f) + f" | {cc.loc[bm, 'mean']:.4f} ({cc.loc[bm, 'sd']:.4f}) | {bm} |")
    out.append("")
    # per-level objectives
    ok2 = ok.copy()
    lv = np.array([json.loads(v) for v in ok2.obj_levels])
    for k in range(lv.shape[1]):
        ok2[f"L{k + 1}"] = lv[:, k]
    out.append("## Per-level objectives (mean over instances and seeds; level 1 = 0.65 B ... level 8 = 1.00 B)")
    out.append("")
    out.append("| budget | method | " + " | ".join(f"L{k + 1}" for k in range(lv.shape[1])) + " |")
    out.append("|---|---|" + "---|" * lv.shape[1])
    for b in BUD:
        for m in FIN + CLS:
            x = ok2[(ok2.budget == b) & (ok2.solver == m)]
            out.append(f"| {b} | {m} | " + " | ".join(f"{x[f'L{k + 1}'].mean():.3f}" for k in range(lv.shape[1])) + " |")
    out.append("")
    out.append("## Wall time (s) per run and over-budget / failure counts")
    out.append("")
    out.append("| budget | method | runs ok | failed | over budget (> 1.05 T + 0.5) | wall min | median | max |")
    out.append("|---|---|---|---|---|---|---|---|")
    for b in BUD:
        for m in FIN + CLS:
            x = A[(A.budget == b) & (A.solver == m)]
            xo = x[x.status == "ok"]
            out.append(f"| {b} | {m} | {len(xo)} | {int((x.status != 'ok').sum())} | {int(xo.over_budget.sum())} | "
                       f"{xo.wall.min():.3f} | {xo.wall.median():.3f} | {xo.wall.max():.3f} |")
    out.append("")
    md = "\n".join(out)
    open(os.path.join(RES, "h2test_summary.md"), "w").write(md + "\n")
    json.dump(dict(verdict=verdict, n_runs=int(len(A)), n_ok=int(len(ok)), n_over=int(ok.over_budget.sum()),
                   n_failed=int((A.status != "ok").sum())), open(os.path.join(RES, "h2test_verdict.json"), "w"),
              indent=1)
    print(md)
    print(json.dumps(verdict, indent=1))


if __name__ == "__main__":
    main()
